### ISSUE TITLE
update to JOSM 13807

### ISSUE THREAD

**Issue by don-vip** [bularcasergiu/ContourOverlappingMerge#3]
Hello,
I've made some changes to `Geometry` class:
* [13805](https://josm.openstreetmap.de/changeset/13805/josm/trunk/src/org/openstreetmap/josm/tools/Geometry.java)
* [13807](https://josm.openstreetmap.de/changeset/13807/josm/trunk/src/org/openstreetmap/josm/tools/Geometry.java)

The plugin needs to be recompiled against latest JOSM and Main-Version increased, see [Plugin incompatibilities](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/warnings3)

```
ContourOverlappingDialog:174,           ContourOverlappingMerge, Priority: Normale
--
boolean org.openstreetmap.josm.tools.Geometry.nodeInsidePolygon(org.openstreetmap.josm.data.osm.Node, java.util.List)


ContourOverlappingDialog:217,           ContourOverlappingMerge, Priority: Normale
--
boolean org.openstreetmap.josm.tools.Geometry.nodeInsidePolygon(org.openstreetmap.josm.data.osm.Node, java.util.List)
```

**Comment by don-vip** [comment]
@kendzi I didn't see you're the current maintainer of this plugin with your [fork](https://github.com/kendzi/ContourOverlappingMerge), can you please fix it?

**Comment by kendzi** [comment]
eh, once you fix something for someone, and you are maintainer. But ok i will fix it

**Comment by kendzi** [comment]
I must say plugin development with ANT and hard-coded links is nightmare :(
I released re-compiled version. As I don't maintain that project, I only make fix for new josm because someone ask me to. Maybe it is good idea to switch that project to official plugin repository? Where bugs fix itself? ;)

**Comment by don-vip** [comment]
The nightmare comes from people hosting JOSM plugins on their personal Github profiles and stop maintain it after a few weeks/months. You are one the few who keep up and I thank you for that :) For this case the easiest solution is to transfer this repository to the @JOSM organization, where we can update plugins when required.
